# Generated by Django 2.2 on 2019-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userid', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('acno', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
